[build]
args_bin = []
cmd = "make build-wasm BIN=gameOfLife"
# Exclude dirs and files
exclude_dir = ["assets", "tmp", "vendor", "testdata", "test"]
exclude_file = []
exclude_regex = ["_test.go"]
# Include dir and files
include_dir = ["cmd", "pkg", "internal", "templates"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
send_interrupt = true
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
